# Generated by Django 5.1.3 on 2024-12-13 18:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tag_remove_project_tags_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
