# Generated by Django 5.1.3 on 2024-12-13 18:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='cv',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.pdf', max_length=255, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
