# Generated by Django 5.1.3 on 2024-12-13 20:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_about_cv_alter_about_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='image',
            new_name='bg',
        ),
        migrations.RemoveField(
            model_name='about',
            name='cv',
        ),
        migrations.AddField(
            model_name='about',
            name='profile',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
