# Generated by Django 5.1.3 on 2024-12-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='cname',
            field=models.TextField(default='Coursera'),
        ),
    ]
