# Generated by Django 5.1.3 on 2025-03-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_image_about_bg_remove_about_cv_about_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='resume_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
