# Generated by Django 5.1.3 on 2024-12-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_certificate_cname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
