# Generated by Django 5.1.3 on 2025-03-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_about_resume_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='about',
            name='resume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
