# Generated by Django 5.1.3 on 2025-03-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_about_resume_url_about_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
