# Generated by Django 5.1.3 on 2024-12-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_certificate_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='cname',
        ),
    ]
