# Generated by Django 5.1.3 on 2025-04-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_about_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
    ]
