# Generated by Django 5.1.3 on 2025-04-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_about_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
