# Generated by Django 5.1.3 on 2024-12-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_about_cv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
