# Generated by Django 5.1.3 on 2026-02-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_visitoranalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='bio',
            field=models.TextField(default="I'm a passionate developer..."),
        ),
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default='Your Name', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='role',
            field=models.CharField(default='Developer', max_length=100),
        ),
    ]
