# Generated by Django 5.1.3 on 2026-07-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_about_bio_about_name_about_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('date_range', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_image', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('color', models.CharField(default='#e0e7ff', help_text='Hex color for background', max_length=50)),
                ('icon_svg', models.TextField(blank=True, help_text='SVG code for icon if not using image', null=True)),
                ('icon_color', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
