"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from environ import Env
import dj_database_url
import cloudinary
from dotenv import load_dotenv
from decouple import config

load_dotenv()  # Load environment variables from .env



env = Env()
Env.read_env()
ENVIRONMENT = env('ENVIRONMENT', default='development')
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#Cloudinary imports
import cloudinary.uploader
import cloudinary.api



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='unsafe-secret-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
if ENVIRONMENT == 'development':
    DEBUG = True
else:
    DEBUG = False

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [
    'https://praneeth-g.vercel.app',
    'https://*.vercel.app',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

# Trust Vercel's proxy for HTTPS (prevents redirect loops)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = False  # Vercel handles SSL termination


# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',  # Correct module name
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "main.apps.MainConfig",
    'cloudinary',
    'storages',
]

MIDDLEWARE = [
    'main.middleware.SimpleCorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # VisitorTrackingMiddleware disabled on serverless (causes DB issues)
    # 'main.middleware.VisitorTrackingMiddleware',
]

APPEND_SLASH = True  # Automatically adds trailing slash

ROOT_URLCONF = 'portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR}/db.sqlite3')
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'  # Indian Standard Time

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'main/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'main/static')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files configuration for Supabase
MEDIA_URL = '/media/'  # URL for accessing media files
# MEDIA_ROOT = os.path.join(BASE_DIR, 'main/staticfiles')

# Remove or comment out local media root if it exists
# MEDIA_ROOT = os.path.join(BASE_DIR, 'main/staticfiles')


cloudinary.config(
    cloud_name=os.getenv('CLOUD_NAME'),
    api_key=os.getenv('API_KEY'),
    api_secret=os.getenv('API_SECRET')
)


# Load from .env (with safe defaults so Django doesn't crash if vars missing)
SUPABASE_S3_ACCESS_KEY = config('SUPABASE_S3_ACCESS_KEY', default='')
SUPABASE_S3_SECRET_KEY = config('SUPABASE_S3_SECRET_KEY', default='')
SUPABASE_S3_REGION_NAME = config('SUPABASE_S3_REGION_NAME', default='us-east-1')
SUPABASE_S3_ENDPOINT_URL = config('SUPABASE_S3_ENDPOINT_URL', default='')
# Supabase Configuration
SUPABASE_URL = env("SUPABASE_URL", default='')
SUPABASE_KEY = env("SUPABASE_KEY", default='')
SUPABASE_BUCKET = 'staticfiles'

# Additional S3-compatible settings for Supabase
SUPABASE_S3_ENDPOINT = f"{SUPABASE_URL}/storage/v1/s3" if SUPABASE_URL else ''
SUPABASE_S3_ACCESS_KEY = env("SUPABASE_S3_ACCESS_KEY", default='')
SUPABASE_S3_SECRET_KEY = env("SUPABASE_S3_SECRET_KEY", default='')

# Django Storage Configuration (Django 5.x style)
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": SUPABASE_S3_ACCESS_KEY,
            "secret_key": SUPABASE_S3_SECRET_KEY,
            "bucket_name": SUPABASE_BUCKET,
            "endpoint_url": SUPABASE_S3_ENDPOINT,
            "region_name": "us-east-1",  # Supabase default
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

